### PR TITLE
Tile component

### PR DESCRIPTION
**Pull request by Ziden**

### CODE REVIEW

**Comment by Cryptomane** [comment]
IT'S ALIVE

**Comment by FeldmannJR** [comment]
def0e77f-e79c-492a-89fd-0f189e5234ec_text
Classy one

**Comment by Ziden** [comment]
> IT'S ALIVE

hahaha yeah it is :D Gonna finish this money machine. Wanna join ? We gonna plan on the next upcoming days.

**Comment by Cryptomane** [comment]
> hahaha yeah it is :D Gonna finish this money machine. Wanna join ? We gonna plan on the next upcoming days.

I'll try to squeeze in a PR or two, according to my availability. Free of charge :P

**Comment by Ziden** [comment]
> > hahaha yeah it is :D Gonna finish this money machine. Wanna join ? We gonna plan on the next upcoming days.
> 
> I'll try to squeeze in a PR or two, according to my availability. Free of charge :P

Free of charge ? That is a good deal !! xD

Jokes around, ill finish this and pitch for investment. Too tired of working to others.
Carlos is onboard. We gonna finish this, decided - if u wanna have a chat on it, could not find u on discord give me a ping !

Good to catchup too long time no see :D

**Pull request merged**
